### ISSUE TITLE
[workbox-precaching] Catch failures to save to cache if the schema is not supported

### ISSUE THREAD

**Issue by WesWedding** [WesWedding/workbox#2]
**Library Affected**:
workbox-precaching

**Browser & Platform**:
Electron 7, 6, 5

**Issue or Feature Request Description**:
Add a catch for when Electron fails to save to a Service Worker cache when the scheme isn't supported.

Driven by Electron failing to save `file` schemes to Cache, even when configured to consider a file scheme as "standard"

See: https://github.com/electron/electron/issues/2831#issuecomment-359707054

**Comment by WesWedding** [comment]
Hacky fix in place.

**Comment by lauri865** [comment]
@WesWedding, do you remember what your hacky fix was? Facing the same issue.

**Comment by lauri865** [comment]
If anyone stumbles here, I've found a hacky fix. There's no way to get serviceWorkers running over the file:// protocol on MacOS. What you could do is serve your static files from an imaginary domain `https://app.localhost`. And then use the following, tricking the browser engine to thinking that you're serving the files over https, while actually rewriting them back to the `file://` protocol requests:

```javascript
const APP_URL = `https://app.localhost`;
protocol.handle("https", (request) => {
    if (request.url.startsWith(APP_URL)) {
      const filePath = request.url.slice(APP_URL.length);
      const filePathToServe = path.join(
        "file://",
        __dirname,
        `../renderer/${MAIN_WINDOW_VITE_NAME}/${filePath}`
      );
      return net.fetch(filePathToServe, { bypassCustomProtocolHandlers: true });
    } else {
      return net.fetch(request, { bypassCustomProtocolHandlers: true });
    }
  });
```

**Comment by WesWedding** [comment]
I don't believe I ever fixed the root problem, either!

Rather, what I fixed was: "my serviceWorker can't install because an uncaught error is being thrown" and the fix was forking the entire workbox project just to add a "log to warnings" catch so it wouldn't cause workbox to subsequently fail to function.  😁

I was developing on a Mac but deploying to Windows so I basically got to just ignore the problem.
